-- BDSS.DATA_SOURCE_CONFIGS definition

-- Drop table

-- DROP TABLE BDSS.DATA_SOURCE_CONFIGS;

CREATE TABLE BDSS.DATA_SOURCE_CONFIGS (
	CONFIG_ID VARCHAR2(36) NOT NULL,
	NAME VARCHAR2(255) NOT NULL,
	DB_TYPE VARCHAR2(50) DEFAULT 'oceanbase',
	HOST VARCHAR2(255) NOT NULL,
	PORT NUMBER(10,0) DEFAULT 2881,
	DATABASE VARCHAR2(128) DEFAULT 'sys',
	USERNAME VARCHAR2(255) NOT NULL,
	PASSWORD VARCHAR2(1000),
	DRIVER_CLASS_NAME VARCHAR2(255),
	JDBC_URL VARCHAR2(1000),
	IS_DEFAULT NUMBER(1,0) DEFAULT 0,
	CREATE_TIME TIMESTAMP(6) DEFAULT current_timestamp,
	UPDATE_TIME TIMESTAMP(6) DEFAULT current_timestamp,
	CONSTRAINT DATA_SOURCE_CONFIGS_OBPK_1776863037128003 PRIMARY KEY (CONFIG_ID)
);
CREATE INDEX IDX_DATA_SOURCE_CONFIGS_NAME ON BDSS.DATA_SOURCE_CONFIGS (NAME);


-- BDSS.IMPORT_TASKS definition

-- Drop table

-- DROP TABLE BDSS.IMPORT_TASKS;

CREATE TABLE BDSS.IMPORT_TASKS (
	TASK_ID VARCHAR2(36) NOT NULL,
	FILE_NAME VARCHAR2(255) NOT NULL,
	TARGET_TABLE VARCHAR2(128) NOT NULL,
	TOTAL_ROWS NUMBER(20,0) DEFAULT 0,
	IMPORTED_ROWS NUMBER(20,0) DEFAULT 0,
	STATUS VARCHAR2(20) DEFAULT 'WAITING',
	FILE_ENCODING VARCHAR2(20) DEFAULT 'UTF-8',
	DELIMITER VARCHAR2(10) DEFAULT ',',
	SKIP_HEADER NUMBER(1,0) DEFAULT 0,
	CREATE_TIME TIMESTAMP(6) DEFAULT current_timestamp,
	START_TIME TIMESTAMP(6),
	END_TIME TIMESTAMP(6),
	ERROR_MESSAGE VARCHAR2(4000),
	BATCH_SIZE NUMBER(10,0) DEFAULT 10000,
	THREAD_COUNT NUMBER(3,0) DEFAULT 4,
	FILE_PATH VARCHAR2(500),
	DATA_SOURCE_CONFIG_ID VARCHAR2(36),
	CONSTRAINT IMPORT_TASKS_OBPK_1776851545796990 PRIMARY KEY (TASK_ID)
);
CREATE INDEX IDX_IMPORT_TASKS_CREATE_TIME ON BDSS.IMPORT_TASKS (CREATE_TIME);
CREATE INDEX IDX_IMPORT_TASKS_STATUS ON BDSS.IMPORT_TASKS (STATUS);


-- BDSS.TEST_DATA definition

-- Drop table

-- DROP TABLE BDSS.TEST_DATA;

CREATE TABLE BDSS.TEST_DATA (
	ID NUMBER(20,0),
	COL_TEXT_01 VARCHAR2(500),
	COL_TEXT_02 VARCHAR2(500),
	COL_TEXT_03 VARCHAR2(500),
	COL_TEXT_04 VARCHAR2(500),
	COL_TEXT_05 VARCHAR2(500),
	COL_NUMBER_01 NUMBER(18,4),
	COL_NUMBER_02 NUMBER(18,4),
	COL_NUMBER_03 NUMBER(18,4),
	COL_NUMBER_04 NUMBER(18,4),
	COL_NUMBER_05 NUMBER(18,4),
	COL_NUMBER_06 NUMBER(18,4),
	COL_NUMBER_07 NUMBER(18,4),
	COL_NUMBER_08 NUMBER(18,4),
	COL_NUMBER_09 NUMBER(18,4),
	COL_NUMBER_10 NUMBER(18,4),
	COL_VARCHAR_01 VARCHAR2(100),
	COL_VARCHAR_02 VARCHAR2(100),
	COL_VARCHAR_03 VARCHAR2(100),
	COL_VARCHAR_04 VARCHAR2(100),
	COL_VARCHAR_05 VARCHAR2(100)
);
CREATE INDEX IDX_TEST_DATA_ID ON BDSS.TEST_DATA (ID);


-- BDSS.IMPORT_BATCHES definition

-- Drop table

-- DROP TABLE BDSS.IMPORT_BATCHES;

CREATE TABLE BDSS.IMPORT_BATCHES (
	BATCH_ID VARCHAR2(36) NOT NULL,
	TASK_ID VARCHAR2(36) NOT NULL,
	BATCH_NUMBER NUMBER(10,0) NOT NULL,
	ROWS_COUNT NUMBER(10,0) NOT NULL,
	START_POSITION NUMBER(20,0) NOT NULL,
	END_POSITION NUMBER(20,0) NOT NULL,
	STATUS VARCHAR2(20) DEFAULT 'PENDING',
	START_TIME TIMESTAMP(6),
	END_TIME TIMESTAMP(6),
	ERROR_MESSAGE VARCHAR2(4000),
	CONSTRAINT IMPORT_BATCHES_OBPK_1776851546257023 PRIMARY KEY (BATCH_ID),
	CONSTRAINT FK_IMPORT_BATCHES_TASK FOREIGN KEY (TASK_ID) REFERENCES BDSS.IMPORT_TASKS(TASK_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IDX_IMPORT_BATCHES_STATUS ON BDSS.IMPORT_BATCHES (STATUS);
CREATE INDEX IDX_IMPORT_BATCHES_TASK_ID ON BDSS.IMPORT_BATCHES (TASK_ID);