spring:
  datasource:
    url: jdbc:oceanbase:oracle://120.55.98.148:2881/sys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&connectTimeout=30000&socketTimeout=300000
    username: sys@oracle_db
    password: change_on_install

import:
  upload:
    path: ./uploads
  batch:
    size: 10000
    thread-count: 4

logging:
  level:
    com.oceanbase: DEBUG
    org.springframework.jdbc: DEBUG
