spring:
  datasource:
    url: 
    username: 
    password: 

import:
  upload:
    path: ./uploads
  batch:
    size: 10000
    thread-count: 4

logging:
  level:
    com.oceanbase: DEBUG
    org.springframework.jdbc: DEBUG
